config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:new, :create, :show, :destroy, :index]
  resources :answers, only: [:create, :destroy] do
    member do
      put "like", to: "answers#like"
      put "dislike", to: "answers#dislike"
    end
  end
  resources :tags, only: [:show]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root  'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :answers, foreign_key: :question_id, dependent: :destroy

  has_and_belongs_to_many :tags

  default_scope -> { order('created_at DESC') }

  validates :author_id, presence: true

  validates :title, presence: true, length: { maximum: 120 }

  validates :content, presence: true


  def self.search(search)
    if search
      # Item.where('game_name LIKE :search OR genre LIKE :search OR console LIKE :search', search: "%#{search}%")
      Question.joins(:tags).where('title LIKE ? OR tags.name LIKE ?', "%#{search}%", "#{search}").uniq
    else
      Question.all
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :signed_in_user, only: [:create, :new]
  before_action :admin_user,     only: :destroy

  def create
    @question = current_user.questions.build(question_params)
    save_tags_qs(@question)
    if @question.save
      current_user.question_count += 1
      current_user.save
      flash[:success] = "Question created!"
      redirect_to question_path(@question)
    else
      render 'questions/new'
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = "Question deleted."
    redirect_to questions_url
  end

  def show
    @question = Question.where(:id => params[:id])[0]
    unless @question
      flash[:warning] = "Question doesn't exist"
      redirect_to(root_path)
    end
    @answer = Answer.new
  end

  def index
    if params[:search]
      @search = params[:search]
      @questions = Question.search(@search).paginate(page: params[:page], per_page: 20)
    else
      @questions = Question.paginate(page: params[:page], per_page: 20)
    end
  end

  def new
    @question = Question.new
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def admin_user
    redirect_to(signin_path) unless current_user.admin?
  end

  def save_tags_qs(question)
    params.require(:question).permit(:tags)
    tags = params.require(:question).permit(:tags)[:tags]
    tags = tags.sub(',', ' ')
    tags = tags.gsub(/[^\w\s]/, "")
    tags = tags.gsub(/\s+/, " ")
    tags.split.each do |tag|
      tag_ = Tag.where(name: tag)[0]
      if tag_
        tag_.question_count += 1
        tag_.save!
        question.tags << tag_
      else
        tag__ = question.tags.new(name: tag)
        tag__.question_count += 1
        tag__.save!
      end
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def short_qs_content(str)
    if str.length > 120
      str[0..120] + '...'
    else
      str
    end
  end
end

app/views/questions/blocks/_qs_thread.html.erb
<div class="am-qs-main shadow-container">
  <div class="row">
    <div class="am-qs-user-info col-sm-3">
      <div>
        <%= image_tag(@question.author.avatar.medium, class: 'img-circle')  %>
      </div>
      <a href="<%= user_path(@question.author) %>"><span><%= @question.author.name %></span></a>
    </div>
    <div class="col-sm-9">
      <div class="am-qs-title">
        <h2><%= link_to @question.title, question_path(@question)%></h2>
      </div>
      <div class="am-qs-body">
        <p>
          <%= @question.content %>
        </p>
        <div class="tags">
          <span>Tags: </span>
          <% @question.tags.each do |tag| %>
            <%= link_to '#'+tag.name, tag_path(tag) , style: "color: #555"%><span>, </span>
          <% end %>
        </div>
        <div class="timestamp">
          Posted <%= time_ago_in_words(@question.created_at) %> ago.
        </div>
      </div>
    </div>
  </div>
</div>

app/views/questions/blocks/_qs_thread_answers.html.erb
<% if @question.answers.empty? %>
  <div class="hidden" id="am-answers-container">
<% else %>
    <div id="am-answers-container" style="height: 500px;">
<% end %>
  <div class=" shadow-container col-xs-12">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#">New</a></li>
      <li><a href="#">Popular</a></li>
    </ul>
    <div class="scroll-container" id="am-ajax">
      <% @question.answers.each do |answer| %>
        <div class="row">
          <div class="am-answer">
            <div class="col-xs-1">
              <div class="am-answer-rating">
                <%= link_to "+", like_answer_path(answer), class: 'vote', method: :put, remote: true %>
                   <span class="votes-count"  data-id="<%= answer.id %>"><%= answer.liked_users.count %></span>
                <%= link_to "-", dislike_answer_path(answer), class: 'vote', method: :put, remote: true %>

              </div>
            </div>
            <div class="am-answer-user-info col-xs-2">
              <div>
                <%= image_tag(answer.answerer.avatar.small, class: 'img-circle')  %>
              </div>
              <a href="<%= user_path(answer.answerer) %>"><span><%= answer.answerer.name %></span></a>
            </div>
            <div class="col-xs-9 am-answer-body">
              <p>
                <%= answer.content %>
              </p>
              <div class="answer-timestamp">
                Posted <%= time_ago_in_words(answer.created_at) %> ago.
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/answer_form' %>

app/views/questions/blocks/qs_index.html.erb
<div class="shadow-container col-md-12">
  <div class="row">
    <div class="am-qss-user-info col-sm-3">
      <div>
        <%= image_tag(question.author.avatar.small, class: 'img-circle')  %>
      </div>
      <a href="<%= user_path(question.author) %>"><span><%= question.author.name %></span></a>
    </div>
  </div>
</div>