config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:new, :create, :show, :destroy, :index]
  resources :answers, only: [:create, :destroy] do
    member do
      put "like", to: "answers#like"
      put "dislike", to: "answers#dislike"
    end
  end
  resources :tags, only: [:show]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root  'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_answer_form.html.erb
  <%= form_for(@answer, remote: true, method: 'post',
               :html => {class: "form-horizontal", id: "answer_form"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :question_id, value: @question.id %>

      <div class="form-group">
        <div class="col-xs-9 controls" id="am-answer-formfield">
          <%= f.text_area :content, :class => "form-control",
                          placeholder: "Your answer", rows: "11", id: "answer-content-field" %>
        </div>
      </div>



      <div class="form-group">
        <div class="col-xs-3">
          <%= f.submit "Answer", class: "btn btn-lg btn-default am-btn", id: "btn-reg" %>
        </div>
      </div>
  <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        The form contains <%= pluralize(object.errors.count, "error") %>.
        <ul>
          <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>

    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <!--<div class="row">-->
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <h3>About us</h3>
          <ul class="list-unstyled">
            <li>
              <a href="#">Why AskMachine?</a>
            </li>
            <li>
              <a href="#">Contacts</a>
            </li>
            <li>
              <a href="#">Privacy</a>
            </li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h3>Help</h3>
          <ul class="list-unstyled">
            <li>
              <a href="#">What is machine learning?</a>
            </li>
            <li>
              <a href="#">How to register?</a>
            </li>
            <li>
              <a href="#">How to ask </a>
            </li>
            <li>
              <a href="#">How to login to your account?</a>
            </li>
          </ul>
        </div>
        <div class="col-sm-4">
          <h3>Social newtorks</h3>
          <ul class="list-unstyled">
            <li>
              <a href="#">VK</a>
            </li>
            <li>
              <a href="#">Facebook</a>
            </li>
            <li>
              <a href="#">Twitter</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-4 col-sm-4">
          <div class="copyright-info">
            <p>
              Copyright &copy; 2016 <%= link_to "Sergey Volodin", 'http://github.com/vileven' %>
              <br/> All Rights Reserved
            </p>
          </div>
        </div>

      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="header container-fluid">
    <div class="navbar-header nav navbar-left">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('am_logo.png', alt: '', width: 50), root_path , class: 'navbar-brand logo', id: 'logo-nav'%>

      <a class="navbar-brand"  href="<%= root_url %>">
        <span id="brand-name">AskMachine</span>
      </a>
    </div>




    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right ">
        <li><%= link_to t("question"), questions_path %></li>
        <% if signed_in? %>
            <li> <%= link_to t("users"), users_path %> </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu am-user-menu">
                <li><%= link_to t("profile"), current_user %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to t("settings"), edit_user_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to t("logout"), signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li>
              <%= link_to "Log in", signin_path %>
            </li>
            <li>
              <%= link_to "Sign up", signup_path %>
            </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>

          <%= form_tag questions_path, method: 'get',
                       class: 'navbar-form navbar-left am-form-search', role: 'search' do %>
              <%= link_to 'Ask', new_question_path, class: 'am-ask-btn btn btn-default' %>
              <%= text_field_tag :search, params[:search],
                                 class: 'form-control header-search-input',
                                 placeholder: 'Search'
              %>
              <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>

          <% end %>


        </li>
      </ul>

    </div>
  </div>

</nav>

app/views/shared/_question_form.html.erb
<div class="row">
  <%= form_for(@question, :html => {class: "form-horizontal"}) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :title, class: "col-sm-3 control-label" %>
        <div class="col-sm-9 controls">
          <%= f.text_field :title, :class => "form-control",
                           placeholder: "Short description of your problem" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :content, class: "col-sm-3 control-label" %>
        <div class="col-sm-9 controls">
          <%= f.text_area :content, :class => "form-control", placeholder: "Question body", rows: "11" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :tags, class: "col-sm-3 control-label"%>
        <div class="col-sm-9 controls">
          <%= f.text_field :tags, :class => "form-control",
                           placeholder:"For example: #NN #Python #LinearRegression", value: "" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-3">
          <%= f.submit "ASK!", class: "btn btn-lg btn-default am-btn", id: "am-btn-ask-form" %>
        </div>
      </div>
  <% end %>
</div>

app/views/shared/_right_menu.html.erb
<div class="fixed">
  <div class="tags">
    <div class="tags-header">
      <span><h2><%= t('top_tags') %></h2></span>
    </div>
    <div class="tags-content">
      <% top_tags.each do |tag|%>
          <%= link_to tag_path(tag) do %>
            <span><%= tag.name %></span>
          <% end %>
      <% end %>
    </div>
  </div>



  <div class="member-top">
    <span><h2><%= t('top_members') %></h2></span>
    <ul class="list-unstyled">
      <% top_members.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
      <% end %>
    </ul>
  </div>
</div>