config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:new, :create, :show, :destroy, :index]
  resources :answers, only: [:create, :destroy] do
    member do
      put "like", to: "answers#like"
      put "dislike", to: "answers#dislike"
    end
  end
  resources :tags, only: [:show]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root  'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_and_belongs_to_many :questions, class_name: 'Question', counter_cache: true

  # scope :top, order('questions_count DESC')

  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.where(id: params[:id])[0]
    unless @tag
      redirect_to(root_path)
      flash[:warning] = "Tag doesn't exist"
    else
      @questions = @tag.questions.paginate(page: params[:page], per_page: 20)
    end
  end
end

app/views/tags/show.html.erb
<% provide(:title, @tag.name) %>
<% content_for :styles do %>
    <%= stylesheet_link_tag 'custom/qs_index' %>
    <%= stylesheet_link_tag 'custom/paginate' %>
<% end %>

<h1>#<%= @tag.name %> :  <%= @tag.question_count %> Questions</h1>
<div class="col-md-12">
  <%= will_paginate @questions %>
</div>

<% @questions.each do |question| %>
    <div class="shadow-container col-md-12">
      <div class="row">
        <div class="am-qss-user-info col-sm-3">
          <div>
            <%= image_tag(question.author.avatar.medium, class: 'img-circle')  %>
          </div>
          <a href="<%= user_path(question.author) %>"><span><%= question.author.name %></span></a>
        </div>
        <div class="am-qss-body col-sm-9">
          <% if current_user.present? && current_user.admin?  %>
              <%= link_to "| delete", question, method: :delete,
                          data: { confirm: "You sure?" } ,
                          style: "float: right;"%>
          <% end %>
          <h3><%= link_to question.title, question_path(question) %></h3>
          <p><%= short_qs_content(question.content) %></p>
          <div class="timestamp1">
            Posted <%= time_ago_in_words(question.created_at) %> ago.
          </div>
        </div>
      </div>
    </div>
<% end %>
<div class="col-md-12">
  <%= will_paginate @questions %>
</div>